### ISSUE TITLE
Exception in production

### ISSUE THREAD

**Issue by MeinAccount** [QFA2021/chshGame#2]
```
chsh_1      | Exception in thread Thread-33435:
chsh_1      | Traceback (most recent call last):
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
chsh_1      |     self.run()
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
chsh_1      |     self._target(*self._args, **self._kwargs)
chsh_1      |   File "/app/qGame/chsh.py", line 109, in referee
chsh_1      |     a = int(alice_response.content)
chsh_1      | AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by MeinAccount** [comment]
```
chsh_1      | Process Process-14:
chsh_1      | Traceback (most recent call last):
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
chsh_1      |     self.run()
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
chsh_1      |     self._target(*self._args, **self._kwargs)
chsh_1      |   File "/usr/local/lib/python3.9/site-packages/eqsn/worker_process.py", line 35, in run
chsh_1      |     item = self.queue.get()
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 122, in get
chsh_1      |     return _ForkingPickler.loads(res)
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 934, in RebuildProxy
chsh_1      |     return func(token, serializer, incref=incref, **kwds)
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 982, in AutoProxy
chsh_1      |     proxy = ProxyType(token, serializer, manager=manager, authkey=authkey,
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 784, in __init__
chsh_1      |     self._incref()
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 839, in _incref
chsh_1      |     dispatch(conn, None, 'incref', (self._id,))
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 93, in dispatch
chsh_1      |     raise convert_to_error(kind, result)
chsh_1      | multiprocessing.managers.RemoteError:
chsh_1      | ---------------------------------------------------------------------------
chsh_1      | Traceback (most recent call last):
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 212, in handle_request
chsh_1      |     result = func(c, *args, **kwds)
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 431, in incref
chsh_1      |     raise ke
chsh_1      |   File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 418, in incref
chsh_1      |     self.id_to_refcount[ident] += 1
chsh_1      | KeyError: '7fb0d162ac10'
chsh_1      | ---------------------------------------------------------------------------
chsh_1      | Exception in thread Thread-9422:
chsh_1      | Traceback (most recent call last):
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
chsh_1      |     self.run()
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
chsh_1      |     self._target(*self._args, **self._kwargs)
chsh_1      |   File "/app/qGame/chsh.py", line 109, in referee
chsh_1      |     a = int(alice_response.content)
chsh_1      | AttributeError: 'NoneType' object has no attribute 'content'
chsh_1      | [30/Sep/2021 08:51:21] "GET /%2FchshGame HTTP/1.0" 200 18704
chsh_1      | Exception in thread Thread-10442:
chsh_1      | Traceback (most recent call last):
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
chsh_1      |     self.run()
chsh_1      |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
chsh_1      |     self._target(*self._args, **self._kwargs)
chsh_1      |   File "/app/qGame/chsh.py", line 109, in referee
chsh_1      |     a = int(alice_response.content)
chsh_1      | AttributeError: 'NoneType' object has no attribute 'content'
```
